# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Continuous Integration

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  PORT: 3001
  ENVIRONMENT: DEVELOPMENT
  DEV_DATABASE_URL: mongodb://localhost:27017/
  DEV_DB: dev
  PROD_DB: prod
  DEV_SERVER_IP: localhost
  PROD_SERVER_IP: 0.0.0.0
  PROJECT_ROOT_PATH: /home/runner/work/File-Management-System-Server/File-Management-System-Server/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.17.4
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.4
        cache: 'npm'
      
    - name: Create mongoDB Docker container      
      run: sudo docker run -d -p 27017:27017 mongo:5.0.4
    
    - name: Create .env file
      run: |
        touch .env
        echo DEV_DATABASE_URL=$DEV_DATABASE_URL >> .env
        echo DEV_DB=$DEV_DB >> .env
        echo DEV_SERVER_IP=$DEV_SERVER_IP >> .env
        echo PORT=$PORT >> .env
        pwd
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
